# ------------------------------------------------------ #
# Tip: sort properties alphabetically. Even nested ones! #
# Tip: all property keys lowercase!!!                    #
# ------------------------------------------------------ #

# Central Database
minecade:
  central-database:
    driver: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/sky_network
    username: root

# Lobby
lobby:
    name: 'aclobby'
    spawn:
        x: 0
        y: 17
        z: 1 
        yaw: 92    
        pitch: 3
        world: pmslobby
    start-countdown: 10 # Time to begin each match

# Match
match:
    ready-countdown: 10 # The time to wait until all users are ready to start the match.
    required-players: 4 # Minimun Players needed to start the match.
    start-countdown: 30 # The time in seconds to wait when the MATCH_PLAYERS limit reached to start the match.
    time: 600 # Match duration time in seconds.
   
# Server
server:
    announcements:
    - '&dVisit skydoesminecraft.com/shop to purchase VIP!'
    - '&dJoin the fun at skydoesminecraft.com for up-to-date information on Sky Networks!'
    - '&dExecute Double Jumps by tapping the space bar twice!'
    - '&dVIP users can join to full servers, visit skydoesminecraft.com/shop to purchase VIP!'
    ban-message: 'You have been banned from sky servers. Appeal at http://skydoesminecraft.com/'
    id: 1
    full-message: 'The server if full, visit skydoesminecraft.com/shop to purchase VIP!'
    max-players: 20 # Match players in the server.
    max-vip-players: 24 # Match players in the server.        
    name: 'AC Server 1'
   
   
 

    
