# ------------------------------------------------------ #
# Tip: sort properties alphabetically. Even nested ones! #
# Tip: all property keys lowercase!!!                    #
# ------------------------------------------------------ #
# Entities root packages
entities:
    package: 'com.minecade.ac.data'

# Server
server:
    announcements:
    - '&dVisit http://skydoesminecraft.com/shop to purchase VIP!'
    - '&dJoin the fun at http://skydoesminecraft.com for up-to-date information on Sky Networks!'
    - '&dVIP users can join to full servers, visit http://skydoesminecraft.com/shop to purchase VIP!'
    id: 1
    name: 'Assassins Creed Server 1'
    vip-players: 5
    players: 75

# Match
match:
    ban-message: 'You have been banned from sky servers. Appeal at http://skydoesminecraft.com/'
    lobby-world-name: 'GBLobbyWorld'
    time: 360 # Match duration time in seconds.
    start-countdown: 20 # The time in seconds to wait when the MATCH_PLAYERS limit reached to start the match.
    ready-countdown: 15 # The time to wait until all runners are ready to start to run.
    required-players: 9 # Minimun Players needed to start the match.
    required-ghostbusters: 3 #Minimun GhostBusters to start the match.
    server-full-message: 'The server if full, visit skydoesminecraft.com/shop to purchase VIP!'
    scoreboard-title: GhostBusters
    scoreboard-players-left: Players Left
    scoreboard-remaining-time: Time Left
    scoreboard-players-to-start: Players to Start
    scoreboard-players-in-match: Players in Match
    souls: Souls
    
# Lobby
lobby:
    spawn:
        pitch: 0
        world: GBLobbyWorld
        x: -5
        y: 49
        yaw: 90
        z: 2

# Central Database
minecade:
  central-database:
    username: ${database.username}
    driver: com.mysql.jdbc.Driver
    password: ${database.password}
    url: ${database.url}
