# ------------------------------------------------------ #
# Tip: sort properties alphabetically. Even nested ones! #
# Tip: all property keys lowercase!!!                    #
# ------------------------------------------------------ #
           
# Entities root packages
entities:
    package: 'com.minecade.ac.data'

# Lobby
lobby:
    name: 'aclobby'
    spawn:
        pitch: 0
        world: aclobby
        x: -1120
        y: 13
        yaw: 92 
        z: 2452    
        pitch: 0

#Logging Level
logging-level: INFO

# Match
match:
    required-players: 6 # Minimun Players needed to start the match.
    start-countdown: 10 # Time to begin each match
    time: 360 # Match duration time in seconds (5 minutes).
  
# Central Database
minecade:
  central-database:
    username: assassinscreed
    driver: com.mysql.jdbc.Driver
    password: 2vj7laev8CXb
    url: jdbc:mysql://172.23.24.95:3306/sky_network
   
# Server
server:
    announcements:
    - '&dVisit skydoesminecraft.com/shop to purchase VIP!'
    - '&dJoin the fun at skydoesminecraft.com for up-to-date information on Sky Networks!'
    - '&dVIP users can join to full servers, visit skydoesminecraft.com/shop to purchase VIP!'
    ban-message: 'You have been banned from sky servers. Appeal at http://skydoesminecraft.com/'
    id: <index>
    full-message: 'The server if full, visit skydoesminecraft.com/shop to purchase VIP!'
    max-players: 24 # Match players in the server.
    max-vip-players: 30 # Match players in the server.        
    name: 'AC Server <index>'
   
