# plugin config for bukkit
name: ${project.name}
main: ${main.class}
version: '${project.version}'
authors: [kvnamo, victorv977]

#load: startup # disabled because we need to load the worlds, to load the world ther server must be loaded.

commands:
    ban:
        description: Ban players
    forcestart:
        description: Skip the validation to wait to complete the minimum players and force to start the game. (Ops only)
    kill:
        description: Blocked command.
        usage: Use /kill
    lowershop:
        description: teleport to lower shop
    me:
        description: Blocked command.
        usage: Use /me
    rank:
        description: "Modify ranks"
        usage: "/rank [player] [rank] [true | false]"
    unban:
        description: Unban players  
    saveworld:
        description: Save modifications on the world the issuer player is in. (in-game only)
    serverinfo:
        description: Get current server info.
        usage: Use /serverinfo
    topshop:
        description: teleport to top shop
        
database: true
