# ------------------------------------------------------ #
# Tip: sort properties alphabetically. Even nested ones! #
# Tip: all property keys lowercase!!!                    #
# ------------------------------------------------------ #
           
# Entities root packages
entities:
    package: 'com.minecade.ac.data'

# Lobby
lobby:
    name: 'aclobby'
    spawn:
        pitch: 0
        world: aclobby
        x: -1120
        y: 13
        yaw: 92 
        z: 2452    
        pitch: 0

#Logging Level
logging-level: INFO

# Match
match:
    lobby-world-name: ACLobby
    required-players: 6 # Minimun Players needed to start the match.
    start-countdown: 10 # Time to begin each match
    time: 360 # Match duration time in seconds (5 minutes).
    ready-countdown: 30 # Time to ready each match
    finish-countdown: 10 # Time to finish each match
    ban-message: 'You have been banned from sky servers. Appeal at http://skydoesminecraft.com/'
    announcements:
    - '&dThe Assassin has to eliminate the 5 victims found in 5 buildings!'
    - '&dPressure plates on diamond blocks give the Assassin 1 experience level.!'
    - '&dThe Royal Navy have to defend the 5 victims found in 5 buildings.!'

# Central Database
minecade:
  central-database:
    username: assassinscreed
    driver: com.mysql.jdbc.Driver
    password: 2vj7laev8CXb
    url: jdbc:mysql://172.23.24.95:3306/sky_network
   
# Server
server:
    announcements:
    - '&dVisit skydoesminecraft.com/shop to purchase VIP!'
    - '&dJoin the fun at skydoesminecraft.com for up-to-date information on Sky Networks!'
    - '&dExecute Double Jumps by tapping the space bar twice!'
    - '&dVIP users can join to full servers, visit skydoesminecraft.com/shop to purchase VIP!'
    - '&dAssassin, use the place finder[compass] to locate the objetives'
    - '&dVIP users have high probability to be assassin every match'
    ban-message: 'You have been banned from sky servers. Appeal at http://skydoesminecraft.com/'
    id: 2
    full-message: 'The server if full, visit skydoesminecraft.com/shop to purchase VIP!'
    max-players: 30 # Match players in the server.
    max-vip-players: 30 # Match players in the server.        
    name: 'AC Server 2'
   
